# Generated by Django 4.2.7 on 2024-06-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='data_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date1',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
